# Generated by Django 4.1.3 on 2023-01-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_customer_images"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AlterField(
            model_name="customer",
            name="birthday",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="fullname",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="customer",
            name="license_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="customer",
            name="nationality",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="customer",
            name="vehicle_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
